---

plugins:
  - jest

env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-restricted-syntax:
    - 0
    - ForOfStatement
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
